### PR TITLE
Update Batch SDK to new API version 2019-08-01.

### PR DESCRIPTION
**Pull request by xingwu1**
Both data-plane and management-plane.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by xingwu1** [comment]
@amarzavery It looks like test failed but not due to new PR.

**Comment by amarzavery** [comment]
@xingwu1 - I have moved to a different team. @michaeljqzq and @yungezz can help you with reviewing and merging this PR.

**Comment by xingwu1** [comment]
@michaeljqzq and @yungezz Can any of you help me to look the test failure?

**Comment by xingwu1** [comment]
@michaeljqzq @yungezz ping...

**Comment by michaeljqzq** [comment]
Hi @xingwu1 , about the CI error, it's not related to your change. I'll fix the error.
By the way, the node sdk is going to be deprecated in near future, we recommend moving to azure-sdk-for-js.

**Comment by xingwu1** [comment]
> Hi @xingwu1 , about the CI error, it's not related to your change. I'll fix the error.
> By the way, the node sdk is going to be deprecated in near future, we recommend moving to azure-sdk-for-js.

I got it. But we won't move to new repo until you port our test code to the new repo. We don't want to publish any new SDK without testing.

**Comment by xingwu1** [comment]
@michaeljqzq any progress?

**Comment by michaeljqzq** [comment]
@xingwu1 , the CI is already fixed.
For this PR, we are contacting with JS sdk team about the test case move.

**Comment by xingwu1** [comment]
> @xingwu1 , the CI is already fixed.
> For this PR, we are contacting with JS sdk team about the test case move.

@michaeljqzq Please include me into the discussion thread.

**Pull request merged**
