### PR TITLE
Update Batch data/management plane to new version 2020-09-01

### PR DESCRIPTION
**Pull request by xingwu1**
Update Batch data/management plane to new version 2020-09-01

### CODE REVIEW

**Comment by xingwu1** [comment]
@qiaozha Could you review PR and merge it?

**Comment by qiaozha** [comment]
@ramya-rao-a  This is data-plane SDK right? Should I take a look at it?

**Comment by ramya-rao-a** [comment]
@qiaozha This PR includes both the data plane and management plane SDKs for Azure Batch

@xingwu1, As we discussed a few months ago, all our future efforts for the Batch SDKs should be done in the azure-sdk-for-js repo.
- https://github.com/Azure/azure-sdk-for-js/pull/9878 is the PR to update the data plane library `@azure/batch` library to use the latest service API. This has tests that were ported from this repo and is the coutnerpart to the `azure-batch` package
- `@azure/arm-batch` which is the counterpart to the `azure-arm-batch` package is 2 years old. @qiaozha and her team will be updating this to use the latest service API and we will help in porting over the tests for this package as well.


Meanwhile, please use https://github.com/Azure/azure-sdk-for-js/pull/9878 to confirm that the changes there are as expected. We will add a note here when the PR for management plane SDK is ready.

**Comment by ramya-rao-a** [comment]
cc @deyaaeldeen

**Pull request closed without merging**
