### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dend**
Preparing for integration to docs.microsoft.com

### CODE REVIEW

**Comment by daschult** [comment]
This looks fine, but for this to have a lasting change it'll have to be put into the generator. Can you explain what the different parts of your change do?

**Comment by dend** [comment]
@daschult this flags the content as part of package documentation, that we can then render under the appropriate package page on docs.microsoft.com. The YAML front-matter should not be affecting any product functionality.

**Comment by daschult** [comment]
Okay, cool. Is this pretty stable or are you still working on the contents of the YAML block?

**Comment by dend** [comment]
@daschult this should be stable.

**Comment by daschult** [comment]
@dend Okay. I'll merge this and then send a PR with the generator changes so you can make sure that I got them correct.

**Comment by dend** [comment]
@daschult sounds good, thanks!

**Pull request merged**
