### PR TITLE
Invalid syntax

### PR DESCRIPTION
**Pull request by compojoom**
The file has invalid syntax and was breaking flowjs.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by compojoom** [comment]
maybe a better patch would be to ignore the .vscode folder all together.

**Comment by ramya-rao-a** [comment]
@qiaozha This change looks good to me. Can you get this merged?

**Comment by qiaozha** [comment]
> @qiaozha This change looks good to me. Can you get this merged?

merged

**Pull request merged**
