### PR TITLE
Update deps

### LINKED ISSUE #2957: npm audit found 119 vulnerabilities
npm init
...

    npm i azure -s

...

    + azure@2.2.1-preview
    added 244 packages from 262 contributors and audited 18326 packages in 19.733s
    found 119 vulnerabilities (7 low, 112 moderate)
      run `npm audit fix` to fix them, or `npm audit` for details

*version:*  2.2.1-preview

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #2957

- Noticed that the root node_modules was being linted--updated .jshintignore to prevent `npm test` from dumping tons of useless linter errors into the console
- Changes `new Buffer` to `Buffer.from` to prevent nodejs deprecation warnings from showing in console at runtime
- Updates deps in root package.json
- Updates deps in `ms-rest` which should be enough to suppress most of the npm audit warnings. Need to publish a new ms-rest after somehow verifying the changes are OK (particularly the update to `request` module).
- Removed gruntfile as it seems to no longer be in use, and removed grunt-related dependencies which had vulnerabilities and did not appear to be under active maintenance

Seems like CI is almost green-- there's just a batch client test which is looking for the request authorization header and not finding it. Not sure what to do about that test.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
CI stalled on the first run then passed on the second. `npm test` fails locally. What?

**Comment by tralamazza** [comment]
`mime` version 2 renamed `lookup()` to `getType()`

https://github.com/Azure/azure-sdk-for-node/blob/master/lib/services/legacyStorage/lib/blob/blobservice.js#L910-L914

[`mime-types`](https://www.npmjs.com/package/mime-types) is sometimes used as an alternative.

**Comment by RikkiGibson** [comment]
Looks like `npm audit` recommended to install a new major version of `mime` even though v1.6.0 has no reported vulnerabilities. Will probably roll back to v1.6.0 as I'd like to avoid updating the actual code of a legacy project.

**Comment by RikkiGibson** [comment]
@xingwu1 I'm going to publish a new patch version of `azure-batch` to resolve an `npm audit` warning related to the moment dependency. The total list of affected packages:

```
azure-batch
azure-arm-batchai
azure-insights
azure-storage-legacy
azure-monitoring
azure-scheduler
azure-asm-website
```

**Comment by RikkiGibson** [comment]
`azure@2.3.0-preview` is out and free of `npm audit` warnings. Thanks for bringing it to our attention @tralamazza.

**Comment by tralamazza** [comment]
@RikkiGibson thank you. Quick question though, why does the [ChangeLog.md](https://github.com/Azure/azure-sdk-for-node/blob/master/ChangeLog.md#20170612-version-230-preview) says 2017 for these releases?

**Comment by RikkiGibson** [comment]
I made an error. Will fix.

**Pull request merged**
