### PR TITLE
try fix xml builder

### PR DESCRIPTION
**Pull request by qiaozha**
This is PR is trying to fix issue https://github.com/Azure/azure-sdk-for-node/issues/5159

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by qiaozha** [comment]
@ramya-rao-a Can you help review my PR, Thanks. I have a email thread discuss about the background.

**Comment by ramya-rao-a** [comment]
@joheredi Please review the changes here on updating the version of xml builder package being used

**Comment by freshlogic** [comment]
v0.9.23 published to NPM an hour ago introduces: Cannot find module 'xmlbuilder/lib/XMLBuilder'

**Comment by qiaozha** [comment]
> v0.9.23 published to NPM an hour ago introduces: Cannot find module 'xmlbuilder/lib/XMLBuilder'

Can you point out to me Where do you get this?

**Comment by freshlogic** [comment]
We have an application that use sazure-sb ~0.11.1 which takes a dependency on azure-common.

With a package.json of:
```
"dependencies": {
        "azure-sb": "~0.11.1"
}
```

And an index.js file of:
```
const azure = require('azure-sb');
```

You'll get: Cannot find module 'xmlbuilder/lib/XMLBuilder'

**Comment by freshlogic** [comment]
Here's a simple reproduction:

[azure.zip](https://github.com/Azure/azure-sdk-for-node/files/4957572/azure.zip)

`npm i`
`node index.js`

```
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module 'xmlbuilder/lib/XMLBuilder'
```

**Comment by qiaozha** [comment]
Okay, got it. Let me see how to fix it and get back to ASAP.

**Comment by qiaozha** [comment]
@freshlogic  I have this PR https://github.com/Azure/azure-sdk-for-node/pull/5182 to fix this issue. I pack a new azure-common package and change the azure-sb dependency into my local azure-common package path and then pack a new azure-sb package then change your package.json dependency into my local azure-sb package. Then I run `node index.js` it works. Can you help to double confirm.

**Pull request merged**
