### PR TITLE
[DoNotMerge] ms-rest-azure-2.6.1 change

### PR DESCRIPTION
**Pull request by qiaozha**
This is the PR to show the change of ms-rest-azure 2.6.1

### CODE REVIEW

**Comment by qiaozha** [comment]
@ramya-rao-a Here's the change for 2.6.1, I create this branch from the current main branch, so there'll be no change on the  adal-node version  bump.

**Comment by ramya-rao-a** [comment]
@qiaozha What I meant in https://github.com/Azure/azure-sdk-for-node/pull/5213 was that we should have a branch that reflects the state of things for ms-rest-azure 2.6.1. This will help us make future hotfixes.

- Create a branch `ms-rest-azure-v2` from master from the point where version 2.6.0 of ms-rest-azure was released
- Make the changes required to update adal-node
- In the future use this branch to make v2 hotfixes for ms-rest-azure

**Comment by qiaozha** [comment]
@ramya-rao-a  I get your point, but my concern is that there's a lot of other changes after 3.0.0 commit and I am worried if we revert those changes and leave the branch there, it may cause other potential issues. I think the branch in this PR can correctly reflect what's the code look like in 2.6.1 for ms-rest-azure and at the same time doesn't revert those changes for other packages.  Let me know if that makes sense to you.

**Comment by ramya-rao-a** [comment]
Understood, that works for me

Thanks @qiaozha 

We can close this PR

**Pull request closed without merging**
