### PR TITLE
resolve-ms-rest-azure-security-issue

### PR DESCRIPTION
**Pull request by qiaozha**
to resolve issue #5212

### CODE REVIEW

**Comment by qiaozha** [comment]
@ramya-rao-a Could you help review this PR ?

**Review by ramya-rao-a — APPROVED** [review]
Changes look good to me

Did you test this with any of the packages to ensure none of the breaking changes in adal-node affect us?

**Comment by qiaozha** [comment]
> Changes look good to me
> 
> Did you test this with any of the packages to ensure none of the breaking changes in adal-node affect us?

I run `npm test` in my local and everything looks good. Is it enough ?

**Comment by ramya-rao-a** [comment]
> I run npm test in my local and everything looks good. Is it enough ?

Please test one of the azure-arm-* packages with the changes being made for ms-rest-azure here

**Comment by qiaozha** [comment]
Just realize all the packages azure-arm-* are using "^2.5.5" in their package,json which means non of them will use this package if we release it. Otherwise we will need to bump and release a new package for all the azure-arm-* packages. @ramya-rao-a  What should we do ?

**Comment by qiaozha** [comment]
By the way, I tested in for storage and it works fine with this new ms-rest-azure.

**Comment by ramya-rao-a** [comment]
> Just realize all the packages azure-arm-* are using "^2.5.5" in their package,json which means non of them will use this package if we release it. Otherwise we will need to bump and release a new package for all the azure-arm-* packages. @ramya-rao-a What should we do ?

Another option is to create a hotfix for ms-rest-azure with version 2.6.1 where you update the adal-node dependency. Given that we have limited investment in the packages in this repo as they are deprecated, this would be a better option in terms of effort.

**Comment by qiaozha** [comment]
Hi @ramya-rao-a , after discussion, in order not to break our customers and make sure this security issue could be resolve at customer side. we will release both 2.6.1 and 3.0.1 for this change, and 2.6.1 will be changed based on 2.6.0 and 3.0.1 will be changed based on 3.0.0.

**Comment by ramya-rao-a** [comment]
That sounds good to me, thanks @qiaozha!

**Comment by ramya-rao-a** [comment]
Can you share the link for the PR for 2.6.1?

**Comment by qiaozha** [comment]
Actually, I already release it, just revert this https://github.com/Azure/azure-sdk-for-node/pull/5101 in my local and bump the adal-node version. I don't think we are going to merge this change in the code ?

**Comment by ramya-rao-a** [comment]
>  don't think we are going to merge this change in the code ?

No, but ideally it would be preferred if a branch was maintained for v2 of ms-rest-azure. What if we had to do another hotfix on top of 2.6.1?

**Comment by qiaozha** [comment]
Okay, I will send out the PR. for the change. Thanks

**Comment by qiaozha** [comment]
@ramya-rao-a here's the PR #5216

**Pull request merged**
