### PR TITLE
Adding Log Analytics query capabilities

### PR DESCRIPTION
**Pull request by alexeldeib**
Hi! This PR is to add client generation for the data plane portion of Log Analytics The corresponding treatment to generation the SDK [can be found here](https://github.com/Azure/azure-rest-api-specs/pull/3244). 

I also wasn't able to find info about some parts of the process like npm release -- looks like there are some dead links around and the adx repo didn't have better info? Looking for some guidance/resources around what my next steps would be to publicly release after review :)

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Ping me at rigibson@microsoft and I can onboard you to our npm publishing flow.

**Comment by RikkiGibson** [comment]
BTW, did #3009 basically do some of this work automatically?

**Comment by alexeldeib** [comment]
Oh -- #3009 is because I added azure-sdk-for-node to the azure-rest-spec repo's README, as well as here. I can remove it from the other repo, since i'm adding the mapping as part of this PR?

The client code is the same, this PR adds 9 files:
- package/package-lock.json
- license file
- azure.js rollup function
- test additions (3 files)
- package_service_mapping 
- readme

**Comment by RikkiGibson** [comment]
I think it's good to have it the config in azure-rest-api-specs. Feel free to close #3009 (or I can if you don't have permission).

**Comment by RikkiGibson** [comment]
Our generator config is slightly strange, but the gist is that package_service_mapping doesn't really get used by the AutorestCI bot, but swagger_to_sdk_config does get used, and all the configs over in azure-rest-api-specs get used.

**Comment by alexeldeib** [comment]
Got it. Made those fixes, and closed the auto PR.

**Pull request merged**
