### PR TITLE
URI encoding done before joining with comma

### LINKED ISSUE #5149: responseFilter parameter not encoded correctly in cognitiveServicesWebSearch
I was trying to use the `responseFilter` option in the `cognitiveServicesWebSearch` service and noticed I wasn't able to add multiple filters. After reading the code, I [noticed the commas](https://github.com/Azure/azure-sdk-for-node/blob/739be14a071b6aa0da9269857b3678f0bd6b2614/lib/services/cognitiveServicesWebSearch/lib/operations/web.js#L407) were part of the `encodeURIComponent` parameter, turning them into `%2C`. 

The API doesn't seem to decode them, so I instead mapped on each item of the array with `encodeURIComponent`, then join with comma.

I've already opened a PR #5148, but I'm still opening this issue anyways in case you need every PR to close an issue :)

## More details
To add more context, running the following code would query at the wrong URL.

```
webSearchApiClient.web.search('montreal', { responseFilter : ["Webpages,Images,Videos,News"] }).then((result) => {
   // ...
}).catch(err => {
   // ...
});
```

Queries at : `https://api.cognitive.microsoft.com/bing/v7.0/search?mkt=en-us&q=montreal&responseFilter=Webpages%2CImages%2CVideos%2CNews`

Should be : `https://api.cognitive.microsoft.com/bing/v7.0/search?mkt=en-us&q=montreal&responseFilter=Webpages,Images,Videos,News`

The error message I'm getting was : 

> Only these values are allowed: Webpages,Images,Videos,News,SpellSuggestions,entities,places,RelatedSearches,Computation,TimeZone,Translations

## Original error body
```
{"_type": "ErrorResponse", "errors": [{"_type": "Error", "code": "InsufficientAuthorization", "message": "Insufficient authorization to access requested resource.", "moreDetails":"Only these values are allowed: Webpages,Images,Videos,News,SpellSuggestions,entities,places,RelatedSearches,Computation,TimeZone,Translations", "parameter": "responseFilter", "value": "Webpages%2CImages%2CVideos%2CNews" }]}
```

### PR DESCRIPTION
**Pull request by rykdesjardins**
Close #5149

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by rykdesjardins** [comment]
To add more context, running the following code would query at the wrong URL.

```
webSearchApiClient.web.search('montreal', { responseFilter : ["Webpages,Images,Videos,News"] }).then((result) => {
   // ...
}).catch(err => {
   // ...
});
```

Queries at : `https://api.cognitive.microsoft.com/bing/v7.0/search?mkt=en-us&q=montreal&responseFilter=Webpages%2CImages%2CVideos%2CNews`

Should be : `https://api.cognitive.microsoft.com/bing/v7.0/search?mkt=en-us&q=montreal&responseFilter=Webpages,Images,Videos,News`

The error message I'm getting was : `{"_type": "ErrorResponse", "errors": [{"_type": "Error", "code": "InsufficientAuthorization", "message": "Insufficient authorization to access requested resource.", "moreDetails":"Only these values are allowed: Webpages,Images,Videos,News,SpellSuggestions,entities,places,RelatedSearches,Computation,TimeZone,Translations", "parameter": "responseFilter", "value": "Webpages%2CImages%2CVideos%2CNews" }]}`

**Comment by ramya-rao-a** [comment]
Thanks for the effort here @rykdesjardins, but we have to close this PR as the library in question here is auto generated and cant take manual fixes. I have laid out the next steps in the linked issue

**Comment by rykdesjardins** [comment]
@ramya-rao-a Thank you for the follow up! And no worries :)

**Pull request closed without merging**
