### PR TITLE
Use AR 0.16.0-Nightly20160316

### PR DESCRIPTION
**Pull request by huangpf**
@amarzavery 
It doesn't seem like ```0.16.0-Nightly20160316``` fixes the problem of enum parsing & comparison?

### CODE REVIEW

**Comment by amarzavery** [comment]
@huangpf - I still have to publish the new clientruntime.

**Comment by huangpf** [comment]
@amarzavery 
I think it's already published? 
* http://azuresdkci.cloudapp.net/job/autorest-nightly/287/console

Otherwise, the gulp command will fail, isn't it?

**Comment by amarzavery** [comment]
@huangpf - client runtime (ms-rest and ms-rest-azure).

**Comment by huangpf** [comment]
Oh, ok. please let me know when it's ready. Thanks~

**Comment by amarzavery** [comment]
@huangpf - I have published new versions of ms-rest and ms-rest-azure. Please update your package.json for compute and test it locally. Make sure that the live sample in examples folder passes.
This PR https://github.com/Azure/azure-sdk-for-node/pull/1662 is merged. Please pull from upstream master

**Comment by huangpf** [comment]
@amarzavery Updated.

**Pull request merged**
