### PR TITLE
Update Compute NodeJS SDK

### PR DESCRIPTION
**Pull request by huangpf**

### CODE REVIEW

**Comment by huangpf** [comment]
@amarzavery Could you please help review? Thanks.

**Comment by amarzavery** [comment]
@huangpf have you updated `lib/services/computeManagement2/package.json`?

**Comment by amarzavery** [comment]
@huangpf  - The CI is failing. Please re-record tests.

**Comment by amarzavery** [comment]
IF you can add atleast 1 test for managed disks scenario then that would be great.

**Comment by huangpf** [comment]
@amarzavery Do I need to update the versions in package.json at the root folder as well?

**Comment by huangpf** [comment]
+ @balajikris

**Pull request merged**
