### PR TITLE
:art: Update via rewrite tasklist example

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit updates tasklist example:
- Express 4.* migration
- migration of Azure module API usage to current version
- templates updates and rendering fixes
- markup update in templates to HTML5

Note: This PR depends on fix #1587. If you are testing it locally please make sure to apply patch from #1587 to `lib/azure.js`.

Thanks!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@peterblazejewicz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by peterblazejewicz** [comment]
The cla.azure.com has 500 status error :8ball:

**Comment by amarzavery** [comment]
I tried the CLA website and it worked well. Can you give it a try one more time?

**Comment by peterblazejewicz** [comment]
Nope, sorry:
```
Request URL:https://cla.azure.com/
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:191.235.177.30:443
Response Headers
view source
Cache-Control:private
Content-Length:2499
Content-Type:text/html; charset=utf-8
Date:Tue, 19 Jan 2016 22:08:29 GMT
Server:Microsoft-IIS/8.0
X-AspNet-Version:4.0.30319
X-AspNetMvc-Version:5.2
X-Powered-By:ASP.NET
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pl,en-US;q=0.8,en;q=0.6,ja;q=0.4
Cache-Control:no-cache
Connection:keep-alive
Cookie:MSFPC=ID=ec7fd1ea065677499b4f0e04e707b2ba&CS=1&LV=201509&V=1; ARRAffinity=6bccd0fb7b1b12bf3bbedca232f108f5c449760888a37a6365d6b2c033a43f50; __utma=199044223.1628486387.1450630643.1451418725.1453234878.3; __utmc=199044223; __utmz=199044223.1450630643.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); mp_super_properties=%7B%22all%22%3A%20%7B%22%24initial_referrer%22%3A%20%22%22%2C%22%24initial_referring_domain%22%3A%20%22%22%7D%2C%22events%22%3A%20%7B%7D%2C%22funnels%22%3A%20%7B%7D%7D; _vwo_uuid_v2=C62E5B74AA62B4918676B89EDA0535C0|b1291422f432079b58017321314647a2
DNT:1
Host:cla.azure.com
Pragma:no-cache
Referer:https://github.com/Azure/azure-sdk-for-node/pull/1588
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
```
On OS X with Chrome/Safari.
Thanks!

**Comment by peterblazejewicz** [comment]
I think this one is lost because of cla robot mishap. Should I close this one and resubmit?

**Comment by peterblazejewicz** [comment]
Cannot fix cla status. Close and resubmit

**Pull request closed without merging**
