### PR TITLE
Update azure-arm-storage from v5.0.0 to v7.0.0

### LINKED ISSUE #4655: StorageManagementClient.blobServices is missing in azure-arm-storage
According to the docs, `blobServices` is supposed to be a property on the StorageManagementClient:
https://docs.microsoft.com/en-us/javascript/api/azure-arm-storage/storagemanagementclient?view=azure-node-latest

However, when initializing a StorageManagementClient, `blobServices` is undefined.
screen shot 2019-02-07 at 5 04 38 pm 2

Without this, it's impossible to manage blobServices properties

### Example code
```
const msRestAzure = require('ms-rest-azure')
const { StorageManagementClient } = require('@azure/arm-storage')

const clientId = process.env.CLIENT_ID
const tenantId = process.env.TENANT_ID
const secret = process.env.APPLICATION_SECRET
const subscriptionId = process.env.AZURE_SUBSCRIPTION_ID

msRestAzure.loginWithServicePrincipalSecret(clientId, secret, tenantId)
  .then((credentials) => {
    const client = new StorageManagementClient(credentials, subscriptionId)
    return Promise.resolve(client)
  })
  .then((client) => {
    console.log(client.blobServices)
  })
  .catch((err) => {
    console.error(err)
  })
```

### PR DESCRIPTION
**Pull request by amclin**
Fixes #4655

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by blueww** [comment]
@RikkiGibson 
Would you please help to review and merge the PR is not problem?
Thanks!

**Comment by mikeharder** [comment]
@kpajdzik, @daschult, @salameer: Do any of you have the context to review this?

**Comment by salameer** [comment]
@RikkiGibson is no longer with the team, please avoid tagging  him in the future

**Comment by kpajdzik** [comment]
I'm going to remove all no longer required dependencies in this PR - https://github.com/Azure/azure-sdk-for-node/pull/4843.

**Pull request closed without merging**
