### PR TITLE
Update docs to use https://graph.windows.net as tokenAudience for graph

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Based on the findings at https://github.com/Azure/azure-sdk-for-node/issues/5176#issuecomment-658029660, it is not always reliable to use `graph` for `tokenAudience` when working with `azure-graph`.

This PR updates the docs to use `https://graph.windows.net` instead

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by ramya-rao-a** [comment]
@willmtemple, Please review.

cc @joshlarsen

**Comment by ramya-rao-a** [comment]
The CI does not like this branch. Created a separate PR in #5187 where all is green.

**Pull request closed without merging**
