### PR TITLE
Add package service mapping file.

### PR DESCRIPTION
**Pull request by fiveisprime**
Required file for documentation generation. I Actually scripted the creation of
this so please review it and let me know if anything is obviously borked.

References #2191

### CODE REVIEW

**Comment by fiveisprime** [comment]
@bradygaster ☝️

**Comment by fiveisprime** [comment]
1. I can't add a header, it's JSON so no comments allowed
2. I'm not sure where to add this, but you're right (also see 3)
3. Right repo (following the python example), I think this should be generated from a gulp task and kept up to date automatically
4. See 3 and yes, exactly. I believe this particular check-in to be a stop-gap to unblock the docs team with some technical debt to get this automated

:)

**Comment by balajikris** [comment]
1. we can put the how-to in a ReadME (developer section) or a Developer ReadMe if one is appropriate.
1. cool, lets have it as is for now and look at integrating it into the gulpfile as one of the tasks. 🤖

**Comment by fiveisprime** [comment]
Ping @balajikris since I don't have merge access 👌

**Pull request merged**
