### PR TITLE
get ratecard api call

### PR DESCRIPTION
**Pull request by ashleyschuett**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ashleyschuett__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ashleyschuett** [comment]
Just signed CLA

**Comment by amarzavery** [comment]
@ashleyschuett - Thanks for the contribution. Most of the libraries in the SDK are auto generated. Just wanted to know if this was hand written? Next time when the commerce team autogenerates their SDK this feature add would be gone if it is not autogenerated. Hence they need to be aware about this.

@moinak3, @Matt-Westphal - Can you please review this and let us know if this is in good shape?

**Comment by ashleyschuett** [comment]
I did hand write it.

**Pull request merged**
