### PR TITLE
Update AKV generated code

### PR DESCRIPTION
**Pull request by Lusitanian**
- Management plane: to latest 2016-10-01
- Data plane: to 7.0-preview

### CODE REVIEW

**Comment by amarzavery** [comment]
@Lusitanian - Can you please update the semantic version of the package in `lib/services/keyVault/package.json`. Also make sure to update the versions of "ms-rest" and "ms-rest-azure" to the latest version respectively.

**Comment by amarzavery** [comment]
@Lusitanian - Please publish the `"azure-arm-keyvault"` and `"azure-keyvault"` packages to npm, following the instructions over [here](https://github.com/Azure/azure-sdk-for-node/blob/master/Documentation/RegeneratingCode.md#publishing-to-npm).

**Comment by Lusitanian** [comment]
@amarzavery the jenkins build seems to fail when i try publishing either package because it's unable to touch this directory: 

`java.io.IOException: Failed to mkdirs: D:/workspace/sdk-for-node-publish`

**Comment by amarzavery** [comment]
interesting. @shawns1 - Can you please take a look a this issue?

**Pull request merged**
