### PR TITLE
Support property aliases in resource provider API.

### PR DESCRIPTION
**Pull request by TianoMS**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TianoMS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by vivsriaus** [comment]
LGTM

**Comment by TianoMS** [comment]
Can we get this merged?

**Comment by TianoMS** [comment]
@amarzavery Can you take a look at this PR?

**Comment by amarzavery** [comment]
closing this in favor of #1822

**Pull request closed without merging**
