### PR TITLE
[Network] Regenerated Network SDK using latest swagger

### PR DESCRIPTION
**Pull request by number213**

### CODE REVIEW

**Comment by DeepakRajendranMsft** [comment]
@balajikris please take a look at this

**Comment by balajikris** [comment]
@number213 -- everything but `package.json` is autogenerated using the latest version of autorest. Correct?

**Comment by number213** [comment]
@balajikris correct

**Comment by balajikris** [comment]
@amarzavery -- should this be regenerated after your update to the templates yesterday?

**Pull request merged**
